# Generated by Django 4.0.4 on 2022-06-11 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swcs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sheet_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=4000, null=True)),
                ('function_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='character_description',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_name',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='character_properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swcs.character')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swcs.sheet_property')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='character_props',
            field=models.ManyToManyField(through='swcs.character_properties', to='swcs.sheet_property'),
        ),
    ]
