# Generated by Django 4.0.4 on 2022-06-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swcs', '0002_sheet_property_character_character_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_image',
            field=models.ImageField(null=True, upload_to='swcs/character_pics/'),
        ),
    ]
