# Generated by Django 4.0.4 on 2022-06-15 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swcs', '0003_character_character_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=128)),
                ('species_description', models.CharField(max_length=4000, null=True)),
                ('species_image', models.ImageField(null=True, upload_to='swcs/species_pics/')),
            ],
        ),
        migrations.RenameField(
            model_name='character_properties',
            old_name='prop',
            new_name='character_property',
        ),
        migrations.CreateModel(
            name='species_properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swcs.species')),
                ('species_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swcs.sheet_property')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='character_species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swcs.species'),
        ),
    ]
