# Generated by Django 4.0.4 on 2022-06-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swcs', '0004_species_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='character_props',
            new_name='props',
        ),
        migrations.AddField(
            model_name='species',
            name='props',
            field=models.ManyToManyField(through='swcs.species_properties', to='swcs.sheet_property'),
        ),
    ]
