# Generated by Django 4.0.4 on 2022-06-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swcs', '0005_rename_character_props_character_props_species_props'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='species_description',
            field=models.CharField(max_length=8000, null=True),
        ),
    ]
