# Generated by Django 4.0.4 on 2022-06-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swcs', '0006_alter_species_species_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='species_description',
            field=models.TextField(null=True),
        ),
    ]
