# Generated by Django 4.0.4 on 2022-06-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swcs', '0007_alter_species_species_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='species_agility',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='species',
            name='species_brawn',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='species',
            name='species_cunning',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='species',
            name='species_intellect',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='species',
            name='species_presence',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='species',
            name='species_starting_xp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='species_strain',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='species_willpower',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='species',
            name='species_wound',
            field=models.IntegerField(null=True),
        ),
    ]
